// demos/vue-nestjs/client/components/MetricsDashboard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { EventData } from 'datasole';
import { useDatasoleEvent } from '../composables/useDatasole';
import type { AppContract } from '../../shared/contract';
import { Event } from '../../shared/contract';

type Metrics = EventData<AppContract, Event.SystemMetrics>;

// One line. That's it. This ref auto-updates from the Web Worker
// whenever the server broadcasts system metrics. No store needed.
const metrics = useDatasoleEvent<Metrics>(Event.SystemMetrics);

// Computed properties compose naturally with the reactive ref —
// they re-evaluate automatically when metrics.value changes.
const uptimeDisplay = computed(() => {
  if (!metrics.value) return '';
  const s = Math.floor(metrics.value.uptime / 1000);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  return (h > 0 ? `${h}h ` : '') + `${m}m ${sec}s`;
});

const memoryPct = computed(() => {
  if (!metrics.value) return 0;
  return Math.round((metrics.value.memoryMB / (metrics.value.totalMemoryGB * 1024)) * 100);
});

const totalMessages = computed(() => {
  if (!metrics.value) return 0;
  return metrics.value.messagesIn + metrics.value.messagesOut;
});
</script>

<template>
  <div class="panel">
    <div class="panel-header">Server Metrics</div>
    <div class="panel-body">
      <div class="panel-help">
        <code>const metrics = useDatasoleEvent(Event.SystemMetrics)</code> — one line, no Pinia, no
        Vuex, no <code>watch()</code>. The ref updates reactively from the Web Worker. Bind it in
        your template like any other ref. Computed properties just work.
      </div>
      <div v-if="!metrics" class="metrics-waiting">Waiting for metrics&hellip;</div>
      <div v-else class="metrics-grid">
        <div class="metric-card">
          <div class="metric-label">Uptime</div>
          <div class="metric-value accent">{{ uptimeDisplay }}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Connections</div>
          <div class="metric-value">{{ metrics.connections }}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">CPU</div>
          <div class="metric-value">{{ metrics.cpuUsage }}<span class="metric-unit">ms</span></div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Heap / RAM</div>
          <div class="metric-value">
            {{ metrics.memoryMB }}<span class="metric-unit">MB ({{ memoryPct }}%)</span>
          </div>
        </div>
        <div class="metric-card">
          <div class="metric-label">CPUs</div>
          <div class="metric-value">{{ metrics.cpuCount }}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Total RAM</div>
          <div class="metric-value">
            {{ metrics.totalMemoryGB }}<span class="metric-unit">GB</span>
          </div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Messages</div>
          <div class="metric-value">
            {{ totalMessages
            }}<span class="metric-unit"
              >({{ metrics.messagesIn }}↓ {{ metrics.messagesOut }}↑)</span
            >
          </div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Server Time</div>
          <div class="metric-value time-value">
            {{ metrics.serverTime }}<span class="metric-unit">{{ metrics.timezone }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.panel {
  display: flex;
  flex-direction: column;
  border-right: 1px solid var(--border);
  overflow: hidden;
}
.panel-header {
  padding: 12px 20px;
  font-size: 0.82rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-dim);
  border-bottom: 1px solid var(--border);
  background: var(--surface);
  flex-shrink: 0;
}
.panel-body {
  flex: 1;
  overflow-y: auto;
  padding: 16px 20px;
}
.metrics-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}
.metric-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 16px;
  transition:
    border-color 0.2s,
    box-shadow 0.3s;
}
.metric-card:hover {
  border-color: var(--accent);
  box-shadow: 0 0 12px rgba(232, 132, 44, 0.08);
}
.panel-help {
  font-size: 0.75rem;
  color: var(--text-dim);
  line-height: 1.5;
  padding-bottom: 10px;
}
.panel-help code {
  font-family: var(--mono);
  font-size: 0.7rem;
  background: var(--surface-hover);
  padding: 1px 5px;
  border-radius: 4px;
}
.metric-label {
  font-size: 0.72rem;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-dim);
  margin-bottom: 6px;
}
.metric-value {
  font-size: 1.6rem;
  font-weight: 700;
  font-family: var(--mono);
  color: var(--text);
  line-height: 1.2;
  transition: color 0.25s ease;
}
.metric-value.accent {
  color: var(--accent);
}
.metric-value.time-value {
  font-size: 1.2rem;
}
.metric-unit {
  font-size: 0.7rem;
  color: var(--text-dim);
  margin-left: 4px;
  font-weight: 400;
}
.metrics-waiting {
  color: var(--text-dim);
  font-size: 0.85rem;
  text-align: center;
  padding: 40px 0;
}
</style>

// demos/react-express/client/components/MetricsDashboard.tsx
import { useMemo } from 'react';
import type { EventData } from 'datasole';
import { useDatasoleEvent } from '../hooks/useDatasole';
import type { AppContract } from '../../shared/contract';
import { Event } from '../../shared/contract';

type Metrics = EventData<AppContract, Event.SystemMetrics>;

function formatUptime(ms: number): string {
  const s = Math.floor(ms / 1000);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  return (h > 0 ? `${h}h ` : '') + `${m}m ${sec}s`;
}

export function MetricsDashboard() {
  // One line. This re-renders only when the server broadcasts new data.
  const metrics = useDatasoleEvent<Metrics>(Event.SystemMetrics);

  // Derived values — just useMemo, no store selectors, no reducers.
  const uptimeDisplay = useMemo(
    () => (metrics ? formatUptime(metrics.uptime) : ''),
    [metrics?.uptime],
  );
  const memoryPct = useMemo(
    () => (metrics ? Math.round((metrics.memoryMB / (metrics.totalMemoryGB * 1024)) * 100) : 0),
    [metrics?.memoryMB, metrics?.totalMemoryGB],
  );
  const totalMessages = useMemo(
    () => (metrics ? metrics.messagesIn + metrics.messagesOut : 0),
    [metrics?.messagesIn, metrics?.messagesOut],
  );

  return (
    <div className="panel">
      <div className="panel-header">Server Metrics</div>
      <div className="panel-body">
        <div className="panel-help">
          <code>useDatasoleEvent(Event.SystemMetrics)</code> — one line, no Redux, no Zustand, no{' '}
          <code>useEffect</code>. Data arrives reactively from the Web Worker. Derive with{' '}
          <code>useMemo</code>.
        </div>
        {!metrics ? (
          <div className="metrics-waiting">Waiting for metrics&hellip;</div>
        ) : (
          <div className="metrics-grid">
            <div className="metric-card">
              <div className="metric-label">Uptime</div>
              <div className="metric-value accent">{uptimeDisplay}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Connections</div>
              <div className="metric-value">{metrics.connections}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">CPU</div>
              <div className="metric-value">
                {metrics.cpuUsage}
                <span className="metric-unit">ms</span>
              </div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Heap / RAM</div>
              <div className="metric-value">
                {metrics.memoryMB}
                <span className="metric-unit">MB ({memoryPct}%)</span>
              </div>
            </div>
            <div className="metric-card">
              <div className="metric-label">CPUs</div>
              <div className="metric-value">{metrics.cpuCount}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Total RAM</div>
              <div className="metric-value">
                {metrics.totalMemoryGB}
                <span className="metric-unit">GB</span>
              </div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Messages</div>
              <div className="metric-value">
                {totalMessages}
                <span className="metric-unit">
                  ({metrics.messagesIn}↓ {metrics.messagesOut}↑)
                </span>
              </div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Server Time</div>
              <div className="metric-value time-value">
                {metrics.serverTime}
                <span className="metric-unit">{metrics.timezone}</span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
